platform :ios,'10.0'
target 'BaseProject' do
#pod 'AFNetworking'
pod 'Masonry'
pod 'YYKit'
#pod 'MJRefresh'
pod 'MBProgressHUD'
#pod 'SDWebImage'
#pod 'Tools', :git => 'https://github.com/chuzhaozhi/Tools.git'
pod 'IQKeyboardManager'
# 选择器
pod 'BRPickerView'
#pod 'SDCycleScrollView'
#pod 'SGPagingView'
#pod 'FDFullscreenPopGesture'
# 数据存储
#pod 'LKDBHelper'
# 选择图片
#pod 'HXPhotoPicker'
# yykit
pod 'YYKit'
pod 'FMDB'
end 
